#cloud-config
autoinstall:
  version: 1
  user:
    - default
    - name: Cloudinit
      passwd: $6$N5/vB1ZzTGKhtR.G$/Xxp1nA1xOtUXyVXKzMNIZ4Ha8DOpoUOCju.RvR83cORkTjt110QGh4f6wX2foqAvZzg8UicvbQUYyZ6gMgqM1
      groups: [sudo]
    - name: Cloudinit2
      passwd: $6$N5/vB1ZzTGKhtR.G$/Xxp1nA1xOtUXyVXKzMNIZ4Ha8DOpoUOCju.RvR83cORkTjt110QGh4f6wX2foqAvZzg8UicvbQUYyZ6gMgqM1
      sudo: False
  package-update: true
  package-upgrade: true
  package_reboot_if_required: true
  packages:
    - vim
    - code
